export const ROUTES = {
  AUTH: {
    LOGIN: '/login',
    FORGOT_PASSWORD: '/forgot-password',
  },
  DASHBOARD: {
    HOME: '/dashboard',
    MEMBERS: '/dashboard/members',
    ACCOUNTS: '/dashboard/accounts',
    SAVINGS_ACCOUNTS: '/dashboard/savings-accounts',
    LOANS: '/dashboard/loans',
    TELLER: '/dashboard/teller',
    TELLER_TRANSFERS: '/dashboard/teller/transfers',
    TELLER_VAULT: '/dashboard/teller/vault',
    TELLER_REPORTS: '/dashboard/teller/reports',
    WORKFLOWS: '/dashboard/workflows',
    REPORTS: '/dashboard/reports',
    MEMBER_REPORTS: '/dashboard/member-reports',
    CLOSING: '/dashboard/closing',
    RECONCILIATION: '/dashboard/reconciliation',
    BUDGET_EXPENSES: '/dashboard/budget-expenses',
    SETTINGS: '/dashboard/settings',
    AUDIT: '/dashboard/audit',
    USERS: '/dashboard/users',
    ROLES: '/dashboard/roles',
    BRANCHES: '/dashboard/branches',
    LOGIN_LOGS: '/dashboard/login-logs',
    TRANSACTIONS: '/dashboard/transactions',
    REVERSALS: '/dashboard/reversals',
    APPROVALS: '/dashboard/approvals',
    ACCOUNT_HEADS: '/dashboard/account-heads',
    JOURNAL_VOUCHERS: '/dashboard/journal-vouchers',
    LEDGER: '/dashboard/ledger',
    OPENING_BALANCES: '/dashboard/opening-balances',
    // Deposit Operations
    DEPOSIT_SCHEMES: '/dashboard/deposits/schemes',
    DEPOSIT_RD: '/dashboard/deposits/rd',
    DEPOSIT_FD: '/dashboard/deposits/fd',
    DEPOSIT_DDS: '/dashboard/deposits/dds',
    DEPOSIT_MIS: '/dashboard/deposits/mis',
    DEPOSIT_REPORTS: '/dashboard/deposits/reports',
    RECEIPT_SETTINGS: '/dashboard/receipts/settings',
    STAFF_SALARY: '/dashboard/staff/salary',
  },
};

export default ROUTES;
